version: '3'

services:
    saver-transit:
        image: pravahio/py-pravah:latest
        volumes:
            - "./transit.py:/usr/src/pravah/transit.py"
            - "../db.py:/usr/src/pravah/db.py"
        environment:
            - PRAVAH_DB_USERNAME=${PRAVAH_DB_USERNAME}
            - PRAVAH_DB_PASSWORD=${PRAVAH_DB_PASSWORD}
            - PRAVAH_DB_HOST=${PRAVAH_DB_HOST}
            - PRAVAH_API_KEY=${PRAVAH_API_KEY}
        command: python transit.py
        network_mode: "host"
